server:
  port: 30000
spring:
  application:
    name: tybs-web-service
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
  client:
  #注册地址
    service-url:
      defaultZone:  http://localhost:8761/eureka