spring:
  application:
    name: zuul-server
server:
  port: 30001
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
  client:
  #注册地址
    service-url:
      defaultZone:  http://localhost:8761/eureka

zuul:
 #路由映射
  routes:
    api-dictionary:
      path: /dictionary/**
      serviceId:  moon-service-dictionary